CREATE OR REPLACE FUNCTION get_mimetype (p_file_extension IN VARCHAR2)
   RETURN VARCHAR2
IS
   v_ext   VARCHAR2(50) := LOWER(TRIM(BOTH '.' FROM p_file_extension));
   v_mime  VARCHAR2(1000);
BEGIN
   v_mime := CASE v_ext
                WHEN 'aac' THEN 'audio/aac'
                WHEN 'abw' THEN 'application/x-abiword'
                WHEN 'arc' THEN 'application/octet-stream'
                WHEN 'avi' THEN 'video/x-msvideo'
                WHEN 'azw' THEN 'application/vnd.amazon.ebook'
                WHEN 'bin' THEN 'application/octet-stream'
                WHEN 'bmp' THEN 'image/bmp'
                WHEN 'bz' THEN 'application/x-bzip'
                WHEN 'bz2' THEN 'application/x-bzip2'
                WHEN 'csh' THEN 'application/x-csh'
                WHEN 'css' THEN 'text/css'
                WHEN 'csv' THEN 'text/csv'
                WHEN 'doc' THEN 'application/msword'
                WHEN 'docx' THEN 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
                WHEN 'eot' THEN 'application/vnd.ms-fontobject'
                WHEN 'epub' THEN 'application/epub+zip'
                WHEN 'es' THEN 'application/ecmascript'
                WHEN 'gif' THEN 'image/gif'
                WHEN 'htm' THEN 'text/html'
                WHEN 'html' THEN 'text/html'
                WHEN 'ico' THEN 'image/x-icon'
                WHEN 'ics' THEN 'text/calendar'
                WHEN 'jar' THEN 'application/java-archive'
                WHEN 'jpeg' THEN 'image/jpeg'
                WHEN 'jpg' THEN 'image/jpeg'
                WHEN 'js' THEN 'application/javascript'
                WHEN 'json' THEN 'application/json'
                WHEN 'mid' THEN 'audio/midi audio/x-midi'
                WHEN 'midi' THEN 'audio/midi audio/x-midi'
                WHEN 'mpeg' THEN 'video/mpeg'
                WHEN 'mpkg' THEN 'application/vnd.apple.installer+xml'
                WHEN 'odp' THEN 'application/vnd.oasis.opendocument.presentation'
                WHEN 'ods' THEN 'application/vnd.oasis.opendocument.spreadsheet'
                WHEN 'odt' THEN 'application/vnd.oasis.opendocument.text'
                WHEN 'oga' THEN 'audio/ogg'
                WHEN 'ogv' THEN 'video/ogg'
                WHEN 'ogx' THEN 'application/ogg'
                WHEN 'otf' THEN 'font/otf'
                WHEN 'png' THEN 'image/png'
                WHEN 'pdf' THEN 'application/pdf'
                WHEN 'ppt' THEN 'application/vnd.ms-powerpoint'
                WHEN 'pptx' THEN 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
                WHEN 'rar' THEN 'application/x-rar-compressed'
                WHEN 'rtf' THEN 'application/rtf'
                WHEN 'sh' THEN 'application/x-sh'
                WHEN 'svg' THEN 'image/svg+xml'
                WHEN 'swf' THEN 'application/x-shockwave-flash'
                WHEN 'tar' THEN 'application/x-tar'
                WHEN 'tif' THEN 'image/tiff'
                WHEN 'tiff' THEN 'image/tiff'
                WHEN 'ts' THEN 'application/typescript'
                WHEN 'ttf' THEN 'font/ttf'
                WHEN 'txt' THEN 'text/plain'
                WHEN 'vsd' THEN 'application/vnd.visio'
                WHEN 'wav' THEN 'audio/wav'
                WHEN 'weba' THEN 'audio/webm'
                WHEN 'webm' THEN 'video/webm'
                WHEN 'webp' THEN 'image/webp'
                WHEN 'woff' THEN 'font/woff'
                WHEN 'woff2' THEN 'font/woff2'
                WHEN 'xhtml' THEN 'application/xhtml+xml'
                WHEN 'xls' THEN 'application/vnd.ms-excel'
                WHEN 'xlsx' THEN 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                WHEN 'xml' THEN 'application/xml'
                WHEN 'xul' THEN 'application/vnd.mozilla.xul+xml'
                WHEN 'zip' THEN 'application/zip'
                WHEN '3gp' THEN 'video/3gpp'
                WHEN '3g2' THEN 'video/3gpp2'
                WHEN '7z' THEN 'application/x-7z-compressed'
                ELSE 'text/plain'
             END;

   RETURN v_mime;

EXCEPTION
   WHEN OTHERS THEN
      RETURN NULL;
END;
